# Generated by Django 5.2.6 on 2025-09-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=1000, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publication_indicator',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
