# Generated by Django 5.2.6 on 2025-09-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="views_counter",
            field=models.IntegerField(default=0, verbose_name="Счетчик просмотров"),
        ),
        migrations.AlterField(
            model_name="products",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(upload_to="images/", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="products",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
