# Generated by Django 5.2.6 on 2025-09-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_products_views_counter_alter_products_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='views_counter',
        ),
    ]
